// Package daemon — eventbus.go implements the in-process message
// backbone for the Mortise daemon. Producers (the connect handler,
// later the agent loop) push ServerEvents into the bus via Publish;
// the bus fans each event out to every currently-subscribed TUI
// client. A slow or disconnected client does not block the producer
// — the bus drops events to a full subscriber buffer and increments
// a counter (visible via DroppedCount for diagnostics).
//
// The bus is a deep module: its single public surface is the set of
// methods on *EventBus. Internally it owns a publish channel (so
// Publish is non-blocking), a subscribers map (so Subscribe /
// Unsubscribe are O(1)), and a single fan-out goroutine started by
// Run. Close is a clean teardown used by Daemon.shutdown.
//
// Subscribers are identified by an opaque clientID string. The
// handler generates a UUID per connection; other producers (agent
// loop, status broadcast) do not subscribe at all — they only call
// Publish.
package daemon

import (
	"context"
	"log/slog"
	"sync"
	"sync/atomic"

	mortisev1 "github.com/AzeemWorsdorfer/Mortise/daemon/gen/mortise/v1"
)

// Buffer sizes are package-level constants so tests can reference
// them without scraping implementation details out of the struct.
const (
	// publishBufferSize is the capacity of the bus's internal
	// publish channel. Producers send to it with a non-blocking
	// select, so a full channel means producers were faster than
	// the fan-out goroutine can drain; in practice the fan-out
	// goroutine is the only consumer and processes one event per
	// short burst, so 128 is plenty.
	publishBufferSize = 128

	// subscriberBufferSize is the per-subscriber channel capacity.
	// 64 events of headroom lets a temporarily-slow client catch
	// up without losing any events; if a client falls further
	// behind than 64 events, we start dropping.
	subscriberBufferSize = 64
)

// EventBus is the in-process fan-out hub for ServerEvents. See
// package doc for the overall design.
type EventBus struct {
	// mu guards subscribers. It is an RWMutex so the hot read path
	// (Run snapshotting the subscriber list under RLock) does not
	// contend with each other; only Subscribe / Unsubscribe /
	// Close take the write lock.
	mu          sync.RWMutex
	subscribers map[string]chan *mortisev1.ServerEvent

	// publishCh is the single entry point for events arriving
	// from producers. Run is the sole consumer; producers send
	// with a non-blocking select so a full publish channel
	// surfaces as a drop rather than a stall.
	publishCh chan *mortisev1.ServerEvent

	// drops counts events that could not be delivered to a
	// subscriber because that subscriber's buffer was full. The
	// counter is process-wide; the bus does not track per-
	// subscriber drops because that information is rarely
	// actionable and would add locking.
	drops atomic.Int64

	// closeMu guards closed so Publish after Close can no-op
	// without racing with Close.
	closeMu sync.Mutex
	closed  bool

	// logger receives structured log lines for drops and
	// lifecycle events. Required; tests pass a no-op logger.
	logger *slog.Logger
}

// NewEventBus returns a ready-to-use bus. Call Run in its own
// goroutine to start fan-out, and Close on shutdown to release
// subscriber channels.
func NewEventBus() *EventBus {
	return &EventBus{
		subscribers: make(map[string]chan *mortisev1.ServerEvent),
		publishCh:   make(chan *mortisev1.ServerEvent, publishBufferSize),
		logger:      slog.Default(),
	}
}

// SetLogger swaps the logger used for drop / lifecycle messages.
// Safe to call once during startup; not synchronized for hot-path
// mutation.
func (b *EventBus) SetLogger(l *slog.Logger) {
	if l == nil {
		return
	}
	b.logger = l
}

// Subscribe registers a new client identified by clientID and
// returns the read end of its dedicated buffered channel. The
// channel is closed by Unsubscribe or Close; receivers should
// range over it or use the comma-ok form.
//
// The clientID is opaque to the bus; callers typically pass a
// per-connection UUID generated by the handler. Reusing a
// clientID replaces the previous subscription (the old channel
// is closed) so the handler can safely re-subscribe on reconnect.
func (b *EventBus) Subscribe(clientID string) <-chan *mortisev1.ServerEvent {
	ch := make(chan *mortisev1.ServerEvent, subscriberBufferSize)
	b.mu.Lock()
	if old, ok := b.subscribers[clientID]; ok {
		// Replace: close the old channel so its receiver
		// goroutine exits cleanly. Safe because any previous
		// holder of clientID is gone.
		close(old)
	}
	b.subscribers[clientID] = ch
	b.mu.Unlock()
	return ch
}

// Unsubscribe removes the subscriber for clientID and closes its
// channel. If clientID is not currently subscribed, Unsubscribe is
// a no-op.
func (b *EventBus) Unsubscribe(clientID string) {
	b.mu.Lock()
	if ch, ok := b.subscribers[clientID]; ok {
		delete(b.subscribers, clientID)
		close(ch)
	}
	b.mu.Unlock()
}

// Publish hands event off to the bus for fan-out. The send is
// non-blocking: if the publish channel is full, the event is
// dropped and the drop counter is incremented. This is the
// producer-side guarantee that a slow subscriber never stalls the
// agent loop.
//
// The event is shared by reference; subscribers must not mutate
// it. Run reads it once and dispatches the same pointer to every
// subscriber.
func (b *EventBus) Publish(event *mortisev1.ServerEvent) {
	if event == nil {
		return
	}
	b.closeMu.Lock()
	if b.closed {
		b.closeMu.Unlock()
		return
	}
	select {
	case b.publishCh <- event:
		b.closeMu.Unlock()
	default:
		// publishCh is full; the fan-out goroutine is behind.
		// Drop the event so producers never block.
		d := b.drops.Add(1)
		b.closeMu.Unlock()
		b.logger.Debug("eventbus: publish channel full, event dropped",
			"drops_total", d,
		)
	}
}

// Run is the fan-out loop. It reads events from publishCh,
// snapshots the current subscriber set under RLock, and delivers
// each event to every subscriber with a non-blocking send. The
// loop exits when ctx is canceled; after Run returns, the bus is
// effectively inert and Close should be called to release
// subscriber channels.
func (b *EventBus) Run(ctx context.Context) {
	for {
		select {
		case <-ctx.Done():
			return
		case ev, ok := <-b.publishCh:
			if !ok {
				return
			}
			b.fanOut(ev)
		}
	}
}

// fanOut delivers ev to every subscriber, dropping on a full
// buffer. The RLock is held for the entire fan-out so a concurrent
// Unsubscribe / Close cannot close a channel that we are about to
// send on. Subscribe / Unsubscribe are rare (once per connect /
// disconnect) and fan-out is a tight loop of non-blocking sends,
// so the contended write lock blocks the connect path only for
// microseconds.
func (b *EventBus) fanOut(ev *mortisev1.ServerEvent) {
	b.mu.RLock()
	defer b.mu.RUnlock()
	for _, ch := range b.subscribers {
		select {
		case ch <- ev:
		default:
			// Subscriber is behind; drop for this client only
			// so other clients still receive the event.
			d := b.drops.Add(1)
			b.logger.Debug("eventbus: subscriber buffer full, event dropped",
				"drops_total", d,
			)
		}
	}
}

// SubscriberCount returns the number of currently-registered
// subscribers. Safe to call from any goroutine.
func (b *EventBus) SubscriberCount() int {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return len(b.subscribers)
}

// DroppedCount returns the cumulative count of events dropped due
// to full buffers (either the publish channel or a per-subscriber
// channel).
func (b *EventBus) DroppedCount() int64 {
	return b.drops.Load()
}

// Close releases every subscriber channel and marks the bus as
// closed. After Close, Publish is a no-op. Close is idempotent.
func (b *EventBus) Close() {
	b.closeMu.Lock()
	if b.closed {
		b.closeMu.Unlock()
		return
	}
	b.closed = true
	b.closeMu.Unlock()

	close(b.publishCh)

	b.mu.Lock()
	for id, ch := range b.subscribers {
		close(ch)
		delete(b.subscribers, id)
	}
	b.mu.Unlock()
}
